/**
 * Jobs API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Options for filtering API results.
 */
export interface FilteringOptions { 
    /**
     * Gets or sets the optional search text for filtering results.
     */
    searchText?: string | null;
}

