/**
 * Jobs API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type JobCategory = 'IT' | 'Administrative' | 'Financial' | 'Educational' | 'Healthcare' | 'Other';

export const JobCategory = {

    It: 'IT' as JobCategory,

    Administrative: 'Administrative' as JobCategory,

    Financial: 'Financial' as JobCategory,

    Educational: 'Educational' as JobCategory,

    Healthcare: 'Healthcare' as JobCategory,

    Other: 'Other' as JobCategory
};

