/**
 * Jobs API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeoCoordinates } from './geoCoordinates';


export interface Location { 
    addressLines: Array<string>;
    city: string;
    stateProvince?: string | null;
    postalCode?: string | null;
    countryCode: string;
    geoLocation?: GeoCoordinates;
}

