/**
 * Jobs API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Parameters for paginating API results.
 */
export interface PaginationParameters { 
    /**
     * Gets or sets the 1-based index of the page to retrieve. Must be greater than 0.
     */
    pageNumber?: number;
    /**
     * Gets or sets the number of items per page. Must be between 1 and 100.
     */
    pageSize?: number;
}

